Embeddings

In [1]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

C:\Users\amitd\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Encode some texts
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]
embeddings = model.encode(sentences)
print(embeddings.shape)
similarities = cosine_similarity(embeddings)
print(f"Similarities shape: {similarities.shape}")
print(f"Similarities: {similarities}")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5303.81it/s]


(3, 768)
Similarities shape: (3, 3)
Similarities: [[1.0000001  0.6816545  0.04919665]
 [0.6816545  1.         0.04208853]
 [0.04919665 0.04208853 1.0000002 ]]


In [3]:
model1 = SentenceTransformer('all-MiniLM-L6-v2')
sentences1 = [
    "My name is Amit.",
    "I am learning AI.",
    "I want to make my career in AI."
    "AI is complex and requires continuous practice.",
    "Practice makes the man perfect."]
embeddings1 = model1.encode(sentences1)
print(embeddings1.shape)
similarities1 = cosine_similarity(embeddings1)
print(f"Similarities shape: {similarities1.shape}")
print(f"Similarities: {similarities1}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3311.03it/s]


(4, 384)
Similarities shape: (4, 4)
Similarities: [[1.0000002  0.33025402 0.12988612 0.10606441]
 [0.33025402 1.         0.656008   0.21835473]
 [0.12988612 0.656008   1.         0.24402717]
 [0.10606441 0.21835473 0.24402717 1.0000004 ]]
