In [33]:
import numpy as np

In [34]:
revenue = np.array([[800,1000,1000],[50,90,200],[1500,250,350]])
expenses = np.array([[300,500,600],[20,40,60],[100,50,90]])

Matrix Broadcasting

In [35]:
profit = np.array([revenue - expenses])
profit

array([[[ 500,  500,  400],
        [  30,   50,  140],
        [1400,  200,  260]]])

In [36]:
price = np.array([50,100,80])
items_sold = np.array([[10,40,400],[50,85,90],[500,600,100]])

In [37]:
price*items_sold

array([[  500,  4000, 32000],
       [ 2500,  8500,  7200],
       [25000, 60000,  8000]])

Dot Product of Matrices

In [38]:
total_price = np.dot(price,items_sold)
total_price

array([45500, 58500, 37000])