Naive Bayes comparing Gaussian and Multinomial

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.datasets import load_wine
wine = load_wine()
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [2]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
print(wine.data, wine.feature_names, wine.frame, wine.target,wine.target_names)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]] ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline'] None [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2] ['class_0' 'cla

In [5]:
df = pd.DataFrame(data= wine.data, columns = wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0


In [6]:
print(df.isna().sum())

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [7]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [8]:
df['target'] = wine.target
df[50:70]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
50,13.05,1.73,2.04,12.4,92.0,2.72,3.27,0.17,2.91,7.20,1.12,2.91,1150.0,0
51,13.83,1.65,2.60,17.2,94.0,2.45,2.99,0.22,2.29,5.60,1.24,3.37,1265.0,0
52,13.82,1.75,2.42,14.0,111.0,3.88,3.74,0.32,1.87,7.05,1.01,3.26,1190.0,0
53,13.77,1.90,2.68,17.1,115.0,3.00,2.79,0.39,1.68,6.30,1.13,2.93,1375.0,0
54,13.74,1.67,2.25,16.4,118.0,2.60,2.90,0.21,1.62,5.85,0.92,3.20,1060.0,0
55,13.56,1.73,2.46,20.5,116.0,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120.0,0
56,14.22,1.70,2.30,16.3,118.0,3.20,3.00,0.26,2.03,6.38,0.94,3.31,970.0,0
57,13.29,1.97,2.68,16.8,102.0,3.00,3.23,0.31,1.66,6.00,1.07,2.84,1270.0,0
58,13.72,1.43,2.50,16.7,108.0,3.40,3.67,0.19,2.04,6.80,0.89,2.87,1285.0,0
59,12.37,0.94,1.36,10.6,88.0,1.98,0.57,0.28,0.42,1.95,1.05,1.82,520.0,1


In [9]:
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3)
X_train

array([[1.242e+01, 2.550e+00, 2.270e+00, ..., 8.600e-01, 3.300e+00,
        3.150e+02],
       [1.245e+01, 3.030e+00, 2.640e+00, ..., 6.700e-01, 1.730e+00,
        8.800e+02],
       [1.217e+01, 1.450e+00, 2.530e+00, ..., 1.450e+00, 2.230e+00,
        3.550e+02],
       ...,
       [1.182e+01, 1.470e+00, 1.990e+00, ..., 9.500e-01, 3.330e+00,
        4.950e+02],
       [1.161e+01, 1.350e+00, 2.700e+00, ..., 9.600e-01, 3.260e+00,
        6.800e+02],
       [1.225e+01, 3.880e+00, 2.200e+00, ..., 6.500e-01, 2.000e+00,
        8.550e+02]], shape=(124, 13))

In [10]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred[:10])

[1 1 2 1 0 1 1 0 1 2]


In [11]:
model.score(X_test, y_test)

0.9814814814814815

In [12]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
mn.score(X_test,y_test)

0.8333333333333334

In [13]:
df1 = df[['alcohol','ash', 'magnesium', 'color_intensity', 'proline']]
df1.head()

,alcohol,ash,magnesium,color_intensity,proline
0,14.23,2.43,127.0,5.64,1065.0
1,13.20,2.14,100.0,4.38,1050.0
2,13.16,2.67,101.0,5.68,1185.0
3,14.37,2.50,113.0,7.80,1480.0
4,13.24,2.87,118.0,4.32,735.0


In [14]:
print(df.isna().sum().sum())
print(wine.target)
df1.fillna('proline')


0
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


,alcohol,ash,magnesium,color_intensity,proline
0,14.23,2.43,127.0,5.64,1065.0
1,13.20,2.14,100.0,4.38,1050.0
2,13.16,2.67,101.0,5.68,1185.0
3,14.37,2.50,113.0,7.80,1480.0
4,13.24,2.87,118.0,4.32,735.0
...,...,...,...,...,...
173,13.71,2.45,95.0,7.70,740.0
174,13.40,2.48,102.0,7.30,750.0
175,13.27,2.26,120.0,10.20,835.0
176,13.17,2.37,120.0,9.30,840.0


In [15]:
input = df[['alcohol','ash', 'magnesium', 'color_intensity', 'proline']]
input.head()

,alcohol,ash,magnesium,color_intensity,proline
0,14.23,2.43,127.0,5.64,1065.0
1,13.20,2.14,100.0,4.38,1050.0
2,13.16,2.67,101.0,5.68,1185.0
3,14.37,2.50,113.0,7.80,1480.0
4,13.24,2.87,118.0,4.32,735.0


In [16]:
target = wine.target
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
X_train

,alcohol,ash,magnesium,color_intensity,proline
33,13.76,2.70,132.0,5.40,1235.0
140,12.93,2.70,96.0,4.60,600.0
107,12.72,2.28,84.0,3.30,488.0
85,12.67,2.24,99.0,2.62,450.0
101,12.60,1.90,88.0,2.45,562.0
...,...,...,...,...,...
31,13.58,2.36,106.0,6.90,1515.0
165,13.73,2.26,88.0,6.62,520.0
118,12.77,1.98,80.0,3.40,372.0
7,14.06,2.61,121.0,5.05,1295.0


In [18]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(y_pred[:10])

[0 2 2 0 2 0 0 2 2 2]


In [19]:
model.score(X_test, y_test)

0.9074074074074074

In [20]:
mn1 = MultinomialNB()
mn1.fit(X_train,y_train)
mn1.score(X_test,y_test)

0.7592592592592593